Select insertItemWithClient(
CAST(${numkey||(null)||BigDecimal}$ as inumkey),
CAST(${alphakey||(null)||String}$ as ialphakey),
CAST(${clientkey||(null)||String}$ as clname),
CAST(${itemname||(null)||String}$ as iname),
CAST(${origin||(null)||String||nullable}$ as iorigin),
CAST(${format||(null)||String||nullable}$ as iformat),
CAST(${subformat||(null)||String||nullable}$ as isubformat),
CAST(${school||(null)||String||nullable}$ as ischool),
CAST(${subject||(null)||String||nullable}$ as isubject),
CAST(${insurance||(null)||BigDecimal}$ as iinsurance),
CAST(${aquisition||(null)||Date}$ as iacquisitiondate),
CAST(${creation||(null)||Integer}$ as icreationyear),
CAST(${description||(null)||String}$ as idescription),
CAST(${email||(null)||String||nullable}$ as email),
CAST(${phonenum||(null)||String||nullable}$ as phonenum),
CAST(${buildingname||(null)||String||nullable}$ as buildingname),
CAST(${buildingnumber||(null)||String||nullable}$ as buildingnum),
CAST(${streetname||(null)||String||nullable}$ as streetname),
CAST(${city||(null)||String||nullable}$ as city),
CAST(${country||(null)||String||nullable}$ as country),
CAST(${region||(null)||String||nullable}$ as region),
CAST(${postal||(null)||String||nullable}$ as postalcode)
);