\COPY ns_t_clients TO ns_t_clients.txt
\COPY ns_t_exhibition_items TO ns_t_exhibition_items.txt
\COPY ns_t_exhibition_locations TO ns_t_exhibition_locations.txt
\COPY ns_t_exhibitions TO ns_t_exhibitions.txt
\COPY ns_t_external_locations TO ns_t_external_locations.txt
\COPY ns_t_internal_locations TO ns_t_internal_locations.txt
\COPY ns_t_item_creaTOrs TO ns_t_item_creators.txt
\COPY ns_t_item_locations TO ns_t_item_locations.txt
\COPY ns_t_item_materials TO ns_t_item_materials.txt
\COPY ns_t_item_transactions TO ns_t_item_transactions.txt
\COPY ns_t_items TO ns_t_items.txt
\COPY ns_t_location_doors TO ns_t_location_doors.txt
\COPY ns_t_locations TO ns_t_locations.txt
\COPY ns_t_materials TO ns_t_materials.txt
\COPY ns_t_materials_subcomponents TO ns_t_materials_subcomponents.txt